/**:
  ros__parameters:
  #KMS_240618
    jerk_weight: 10.0        # weight for "smoothness" cost for jerk
    over_v_weight: 100000.0  # weight for "over speed limit" cost #1000.0
    over_a_weight: 5000.0    # weight for "over accel limit" cost #800.0
    over_j_weight: 2000.0    # weight for "over jerk limit" cost #900.0
    jerk_filter_ds: 0.1      # resampling ds for jerk filter
