/**:
  ros__parameters:
    pseudo_jerk_weight: 100.0 #1000.0 # weight for "smoothness" cost #HJK_240619 100.0
    over_v_weight: 100000.0 #1000.0 #KMS_240621    # weight for "over speed limit" cost #HJK_240619 100000.0
    over_a_weight: 5000.0 #1000.0 #KMS_240621  # weight for "over accel limit" cost
